# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Build is starting"
  displayName: 'Start build'
  

- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- script: echo "Build is finished"
  displayName: 'Finish build'
  
- publish: $(System.DefaultWorkingDirectory)/ci1.txt
  artifact: ci1
  
- publish: $(System.DefaultWorkingDirectory)/ci2.txt
  artifact: ci2
  
